#############################################################################
# Makefile for building: butterfly
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  butterfly-qt.pro
# Template: app
# Command: C:/Qt/5.3.2/5.3/mingw482_32/bin/qmake.exe BOOST_INCLUDE_PATH=libs/boost_1_55_0 BOOST_LIB_PATH=libs/boost_1_55_0/stage/lib BOOST_LIB_SUFFIX=-mgw48-mt-1_55 OPENSSL_INCLUDE_PATH=libs/openssl-1.0.1g/include OPENSSL_LIB_PATH=libs/openssl-1.0.1g BDB_INCLUDE_PATH=libs/db-4.8.30.NC/build_unix BDB_LIB_PATH=libs/db-4.8.30.NC/build_unix MINIUPNPC_INCLUDE_PATH=libs/miniupnpc-1.9 MINIUPNPC_LIB_PATH=libs/miniupnpc-1.9 "QMAKE_CXXFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" "QMAKE_CFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" -o Makefile butterfly-qt.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/Qt/5.3.2/5.3/mingw482_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: butterfly-qt.pro ../Qt/5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf ../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/qdevice.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/device_config.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/common/shell-unix.conf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/qconfig.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/default_post.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/qt.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/resources.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/moc.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/opengl.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/uic.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/yacc.prf \
		../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/lex.prf \
		butterfly-qt.pro \
		C:/Qt/5.3.2/5.3/mingw482_32/lib/qtmain.prl \
		C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Core.prl \
		C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5WebKitWidgets.prl \
		C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5WebKit.prl \
		C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Widgets.prl \
		C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Network.prl \
		C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Gui.prl
	$(QMAKE) BOOST_INCLUDE_PATH=libs/boost_1_55_0 BOOST_LIB_PATH=libs/boost_1_55_0/stage/lib BOOST_LIB_SUFFIX=-mgw48-mt-1_55 OPENSSL_INCLUDE_PATH=libs/openssl-1.0.1g/include OPENSSL_LIB_PATH=libs/openssl-1.0.1g BDB_INCLUDE_PATH=libs/db-4.8.30.NC/build_unix BDB_LIB_PATH=libs/db-4.8.30.NC/build_unix MINIUPNPC_INCLUDE_PATH=libs/miniupnpc-1.9 MINIUPNPC_LIB_PATH=libs/miniupnpc-1.9 "QMAKE_CXXFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" "QMAKE_CFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" -o Makefile butterfly-qt.pro
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/spec_pre.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/qdevice.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/device_config.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/common/shell-unix.conf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/qconfig.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/qt_functions.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/qt_config.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/spec_post.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/default_pre.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/resolve_config.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/default_post.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/rtti.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/precompile_header.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/warn_on.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/qt.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/resources.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/moc.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/opengl.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/uic.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/win32/windows.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/testcase_targets.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/exceptions.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/yacc.prf:
../Qt/5.3.2/5.3/mingw482_32/mkspecs/features/lex.prf:
butterfly-qt.pro:
C:/Qt/5.3.2/5.3/mingw482_32/lib/qtmain.prl:
C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Core.prl:
C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5WebKitWidgets.prl:
C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5WebKit.prl:
C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Widgets.prl:
C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Network.prl:
C:/Qt/5.3.2/5.3/mingw482_32/lib/Qt5Gui.prl:
qmake: FORCE
	@$(QMAKE) BOOST_INCLUDE_PATH=libs/boost_1_55_0 BOOST_LIB_PATH=libs/boost_1_55_0/stage/lib BOOST_LIB_SUFFIX=-mgw48-mt-1_55 OPENSSL_INCLUDE_PATH=libs/openssl-1.0.1g/include OPENSSL_LIB_PATH=libs/openssl-1.0.1g BDB_INCLUDE_PATH=libs/db-4.8.30.NC/build_unix BDB_LIB_PATH=libs/db-4.8.30.NC/build_unix MINIUPNPC_INCLUDE_PATH=libs/miniupnpc-1.9 MINIUPNPC_LIB_PATH=libs/miniupnpc-1.9 "QMAKE_CXXFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" "QMAKE_CFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" -o Makefile butterfly-qt.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) C:/butterflycoin/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/butterflycoin/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

C:/butterflycoin/src/leveldb/libleveldb.a: FORCE
	cd C:/butterflycoin/src/leveldb && CC=gcc CXX=g++ TARGET_OS=OS_WINDOWS_CROSSCOMPILE $(MAKE) OPT="-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing -O2" libleveldb.a libmemenv.a && ranlib C:/butterflycoin/src/leveldb/libleveldb.a && ranlib C:/butterflycoin/src/leveldb/libmemenv.a

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
